### ISSUE TITLE
search API documentation

### ISSUE THREAD

**Issue by rlregist** [censys/censys-python#388] opened 2022-10-19 05:35 UTC
On the usage page:  https://censys-python.readthedocs.io/en/stable/usage-v2.html#search

I found that the documentation for multiple pages of search results doesn't work as is:
```
# Multiple pages of search results
query = h.search("service.service_name: HTTP", per_page=5, pages=2)
for page in query:
    print(page)
```

This is what I found to work instead:
```
# Multiple pages of search results
query = h.search("service.service_name: HTTP", per_page=5, pages=2)
for page in range(query.pages):
    print(query)
```

**Comment by thehappydinoa** [comment] 2022-10-19 12:53
Hi @rlregist,

Thank you for bringing this to our attention. Can I ask which version of censys and of python you have installed?

**Comment by rlregist** [comment] 2022-10-19 14:42
Hi @thehappydinoa,

I'm using Censys Python Version: 2.1.8 and Python 3.9.12.

**Comment by thehappydinoa** [comment] 2023-04-25 19:18
Hi there, I was unable to reproduce this specific issue. The first example you provided seems to work with no issues. The second example that you provided only prints the page number, not any content from the page itself. I am going to close this issue, but please feel free to reopen it if your issue was not solved.

**Closed by thehappydinoa** 2023-04-25 19:18 UTC
Labels: type: bug, type: documentation
